site_name: HNSSearch
site_url: "https://dev.hnssearch.io"
#theme: readthedocs
nav:
    - Home: index.md
    - About: about.md
    - LINDA: linda.md
    - Meilisearch: meilisearch.md
    - Handshake: handshake.md